# Generated by Django 4.1.7 on 2023-11-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(default='default/default.jpg', upload_to='profile_images/')),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(max_length=15)),
                ('pressure', models.CharField(max_length=15)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('treated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(default='default/default.jpg', upload_to='profile_images/')),
                ('area_of_specialist', models.CharField(choices=[('Doctor', 'Doctor'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateTimeField(auto_now_add=True)),
                ('summary_note', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.service')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='receptionist',
            field=models.ForeignKey(limit_choices_to={'area_of_specialist': 'Receptionist'}, on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.specialist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treated_by',
            field=models.ForeignKey(limit_choices_to={'area_of_specialist': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients_treated', to='hospitalApp.specialist'),
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.specialist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DentalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dental_visit', models.DateTimeField(blank=True, null=True)),
                ('dental_procedures', models.TextField(blank=True)),
                ('brushing_frequency', models.CharField(blank=True, max_length=50)),
                ('flossing_frequency', models.CharField(blank=True, max_length=50)),
                ('toothpaste_used', models.CharField(blank=True, max_length=100)),
                ('mouthwash_used', models.CharField(blank=True, max_length=100)),
                ('experiencing_discomfort', models.BooleanField(default=False)),
                ('sensitivity_description', models.TextField(blank=True)),
                ('gum_bleeding', models.BooleanField(default=False)),
                ('gum_swelling', models.BooleanField(default=False)),
                ('gum_tenderness', models.BooleanField(default=False)),
                ('gum_changes_description', models.TextField(blank=True)),
                ('sugary_food_frequency', models.CharField(blank=True, max_length=50)),
                ('acidic_food_frequency', models.CharField(blank=True, max_length=50)),
                ('impacting_habits', models.TextField(blank=True)),
                ('medications_impacting_oral_health', models.TextField(blank=True)),
                ('medical_conditions_impacting_dental_care', models.TextField(blank=True)),
                ('cosmetic_interests', models.TextField(blank=True)),
                ('oral_care_guidance', models.TextField(blank=True)),
                ('routine_checkup_due', models.BooleanField(default=False)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
